/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedSolutionsRouteImport } from './routes/_authenticated/solutions'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as AuthenticatedStaffAnalyticsRouteImport } from './routes/_authenticated/staff.analytics'
import { Route as AuthenticatedStaffAuditRouteImport } from './routes/_authenticated/staff.audit'
import { Route as AuthenticatedStaffBiRouteImport } from './routes/_authenticated/staff.bi'
import { Route as AuthenticatedStaffDocumentosRouteImport } from './routes/_authenticated/staff.documentos'
import { Route as AuthenticatedStaffSectorsRouteImport } from './routes/_authenticated/staff.sectors'
import { Route as AuthenticatedStaffSolutionsRouteImport } from './routes/_authenticated/staff.solutions'
import { Route as AuthenticatedStaffTicketsRouteImport } from './routes/_authenticated/staff.tickets'
import { Route as AuthenticatedTicketsIdRouteImport } from './routes/_authenticated/tickets.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicMetricsRouteImport } from './routes/api/public/metrics'
import { Route as AuthenticatedStaffTicketsIdRouteImport } from './routes/_authenticated/staff.tickets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolutionsRoute = AuthenticatedSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffAnalyticsRoute =
  AuthenticatedStaffAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAuditRoute = AuthenticatedStaffAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffBiRoute = AuthenticatedStaffBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedStaffDocumentosRoute =
  AuthenticatedStaffDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSectorsRoute =
  AuthenticatedStaffSectorsRouteImport.update({
    id: '/sectors',
    path: '/sectors',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffSolutionsRoute =
  AuthenticatedStaffSolutionsRouteImport.update({
    id: '/solutions',
    path: '/solutions',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffTicketsRoute =
  AuthenticatedStaffTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedTicketsIdRoute = AuthenticatedTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTicketsRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetricsRoute = ApiPublicMetricsRouteImport.update({
  id: '/api/public/metrics',
  path: '/api/public/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffTicketsIdRoute =
  AuthenticatedStaffTicketsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedStaffTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setores': typeof SetoresRoute
  '/solucoes': typeof SolucoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/docs/api': typeof DocsApiRoute
  '/staff/analytics': typeof AuthenticatedStaffAnalyticsRoute
  '/staff/audit': typeof AuthenticatedStaffAuditRoute
  '/staff/bi': typeof AuthenticatedStaffBiRoute
  '/staff/documentos': typeof AuthenticatedStaffDocumentosRoute
  '/staff/sectors': typeof AuthenticatedStaffSectorsRoute
  '/staff/solutions': typeof AuthenticatedStaffSolutionsRoute
  '/staff/tickets': typeof AuthenticatedStaffTicketsRouteWithChildren
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/staff/tickets/$id': typeof AuthenticatedStaffTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setores': typeof SetoresRoute
  '/solucoes': typeof SolucoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/solutions': typeof AuthenticatedSolutionsRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/docs/api': typeof DocsApiRoute
  '/staff/analytics': typeof AuthenticatedStaffAnalyticsRoute
  '/staff/audit': typeof AuthenticatedStaffAuditRoute
  '/staff/bi': typeof AuthenticatedStaffBiRoute
  '/staff/documentos': typeof AuthenticatedStaffDocumentosRoute
  '/staff/sectors': typeof AuthenticatedStaffSectorsRoute
  '/staff/solutions': typeof AuthenticatedStaffSolutionsRoute
  '/staff/tickets': typeof AuthenticatedStaffTicketsRouteWithChildren
  '/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/staff/tickets/$id': typeof AuthenticatedStaffTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setores': typeof SetoresRoute
  '/solucoes': typeof SolucoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/solutions': typeof AuthenticatedSolutionsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/docs/api': typeof DocsApiRoute
  '/_authenticated/staff/analytics': typeof AuthenticatedStaffAnalyticsRoute
  '/_authenticated/staff/audit': typeof AuthenticatedStaffAuditRoute
  '/_authenticated/staff/bi': typeof AuthenticatedStaffBiRoute
  '/_authenticated/staff/documentos': typeof AuthenticatedStaffDocumentosRoute
  '/_authenticated/staff/sectors': typeof AuthenticatedStaffSectorsRoute
  '/_authenticated/staff/solutions': typeof AuthenticatedStaffSolutionsRoute
  '/_authenticated/staff/tickets': typeof AuthenticatedStaffTicketsRouteWithChildren
  '/_authenticated/tickets/$id': typeof AuthenticatedTicketsIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/metrics': typeof ApiPublicMetricsRoute
  '/_authenticated/staff/tickets/$id': typeof AuthenticatedStaffTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/reset-password'
    | '/setores'
    | '/solucoes'
    | '/dashboard'
    | '/documentos'
    | '/perfil'
    | '/solutions'
    | '/staff'
    | '/tickets'
    | '/docs/api'
    | '/staff/analytics'
    | '/staff/audit'
    | '/staff/bi'
    | '/staff/documentos'
    | '/staff/sectors'
    | '/staff/solutions'
    | '/staff/tickets'
    | '/tickets/$id'
    | '/api/public/health'
    | '/api/public/metrics'
    | '/staff/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/reset-password'
    | '/setores'
    | '/solucoes'
    | '/dashboard'
    | '/documentos'
    | '/perfil'
    | '/solutions'
    | '/staff'
    | '/tickets'
    | '/docs/api'
    | '/staff/analytics'
    | '/staff/audit'
    | '/staff/bi'
    | '/staff/documentos'
    | '/staff/sectors'
    | '/staff/solutions'
    | '/staff/tickets'
    | '/tickets/$id'
    | '/api/public/health'
    | '/api/public/metrics'
    | '/staff/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/esqueci-senha'
    | '/login'
    | '/reset-password'
    | '/setores'
    | '/solucoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/perfil'
    | '/_authenticated/solutions'
    | '/_authenticated/staff'
    | '/_authenticated/tickets'
    | '/docs/api'
    | '/_authenticated/staff/analytics'
    | '/_authenticated/staff/audit'
    | '/_authenticated/staff/bi'
    | '/_authenticated/staff/documentos'
    | '/_authenticated/staff/sectors'
    | '/_authenticated/staff/solutions'
    | '/_authenticated/staff/tickets'
    | '/_authenticated/tickets/$id'
    | '/api/public/health'
    | '/api/public/metrics'
    | '/_authenticated/staff/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetoresRoute: typeof SetoresRoute
  SolucoesRoute: typeof SolucoesRoute
  DocsApiRoute: typeof DocsApiRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMetricsRoute: typeof ApiPublicMetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solutions': {
      id: '/_authenticated/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof AuthenticatedSolutionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/analytics': {
      id: '/_authenticated/staff/analytics'
      path: '/analytics'
      fullPath: '/staff/analytics'
      preLoaderRoute: typeof AuthenticatedStaffAnalyticsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/audit': {
      id: '/_authenticated/staff/audit'
      path: '/audit'
      fullPath: '/staff/audit'
      preLoaderRoute: typeof AuthenticatedStaffAuditRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/bi': {
      id: '/_authenticated/staff/bi'
      path: '/bi'
      fullPath: '/staff/bi'
      preLoaderRoute: typeof AuthenticatedStaffBiRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/documentos': {
      id: '/_authenticated/staff/documentos'
      path: '/documentos'
      fullPath: '/staff/documentos'
      preLoaderRoute: typeof AuthenticatedStaffDocumentosRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/sectors': {
      id: '/_authenticated/staff/sectors'
      path: '/sectors'
      fullPath: '/staff/sectors'
      preLoaderRoute: typeof AuthenticatedStaffSectorsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/solutions': {
      id: '/_authenticated/staff/solutions'
      path: '/solutions'
      fullPath: '/staff/solutions'
      preLoaderRoute: typeof AuthenticatedStaffSolutionsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/tickets': {
      id: '/_authenticated/staff/tickets'
      path: '/tickets'
      fullPath: '/staff/tickets'
      preLoaderRoute: typeof AuthenticatedStaffTicketsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/tickets/$id': {
      id: '/_authenticated/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof AuthenticatedTicketsIdRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/metrics': {
      id: '/api/public/metrics'
      path: '/api/public/metrics'
      fullPath: '/api/public/metrics'
      preLoaderRoute: typeof ApiPublicMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/tickets/$id': {
      id: '/_authenticated/staff/tickets/$id'
      path: '/$id'
      fullPath: '/staff/tickets/$id'
      preLoaderRoute: typeof AuthenticatedStaffTicketsIdRouteImport
      parentRoute: typeof AuthenticatedStaffTicketsRoute
    }
  }
}

interface AuthenticatedStaffTicketsRouteChildren {
  AuthenticatedStaffTicketsIdRoute: typeof AuthenticatedStaffTicketsIdRoute
}

const AuthenticatedStaffTicketsRouteChildren: AuthenticatedStaffTicketsRouteChildren =
  {
    AuthenticatedStaffTicketsIdRoute: AuthenticatedStaffTicketsIdRoute,
  }

const AuthenticatedStaffTicketsRouteWithChildren =
  AuthenticatedStaffTicketsRoute._addFileChildren(
    AuthenticatedStaffTicketsRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAnalyticsRoute: typeof AuthenticatedStaffAnalyticsRoute
  AuthenticatedStaffAuditRoute: typeof AuthenticatedStaffAuditRoute
  AuthenticatedStaffBiRoute: typeof AuthenticatedStaffBiRoute
  AuthenticatedStaffDocumentosRoute: typeof AuthenticatedStaffDocumentosRoute
  AuthenticatedStaffSectorsRoute: typeof AuthenticatedStaffSectorsRoute
  AuthenticatedStaffSolutionsRoute: typeof AuthenticatedStaffSolutionsRoute
  AuthenticatedStaffTicketsRoute: typeof AuthenticatedStaffTicketsRouteWithChildren
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAnalyticsRoute: AuthenticatedStaffAnalyticsRoute,
  AuthenticatedStaffAuditRoute: AuthenticatedStaffAuditRoute,
  AuthenticatedStaffBiRoute: AuthenticatedStaffBiRoute,
  AuthenticatedStaffDocumentosRoute: AuthenticatedStaffDocumentosRoute,
  AuthenticatedStaffSectorsRoute: AuthenticatedStaffSectorsRoute,
  AuthenticatedStaffSolutionsRoute: AuthenticatedStaffSolutionsRoute,
  AuthenticatedStaffTicketsRoute: AuthenticatedStaffTicketsRouteWithChildren,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedTicketsRouteChildren {
  AuthenticatedTicketsIdRoute: typeof AuthenticatedTicketsIdRoute
}

const AuthenticatedTicketsRouteChildren: AuthenticatedTicketsRouteChildren = {
  AuthenticatedTicketsIdRoute: AuthenticatedTicketsIdRoute,
}

const AuthenticatedTicketsRouteWithChildren =
  AuthenticatedTicketsRoute._addFileChildren(AuthenticatedTicketsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedSolutionsRoute: typeof AuthenticatedSolutionsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedSolutionsRoute: AuthenticatedSolutionsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetoresRoute: SetoresRoute,
  SolucoesRoute: SolucoesRoute,
  DocsApiRoute: DocsApiRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMetricsRoute: ApiPublicMetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
